### ISSUE TITLE
Crash ConcurrentModificationException

### ISSUE THREAD

**Issue by shuvashish76** [TheRedSpy15/LTECleanerFOSS#240]
**Describe the bug**
Can't recall why crashed so I can't reproduce the same behaviour...

**Crash logs**
```
FATAL EXCEPTION: Thread-2
Process: theredspy15.ltecleanerfoss, PID: 14153
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at u2.c.g(:3)
	at theredspy15.ltecleanerfoss.controllers.MainActivity.z(:14)
	at v2.b.run(:17)
	at java.lang.Thread.run(Thread.java:764)
```

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab4 8 plus
 - OS: Android 8.1.0
 - App Version: 4.9.5 (58)
 - Downloaded from: F-Droid

**Comment by TheRedSpy15** [comment]
How often does it occur? I've seen this sort of crash since the app was first published. But it seems to happen almost randomly. It's just the threads in java getting all screwed up

I am planning on converting the project to kotlin instead of java here soon, which should reduce of often this happens, since kotlin does threading a bit differently

**Comment by shuvashish76** [comment]
Not sure. My [Scoop](https://github.com/TacoTheDank/Scoop) app not active most of the time. I think I got this crash 1st time.

**Comment by TheRedSpy15** [comment]
fixed 8d92ef7490ff92e1708323c61e998767c0bae295

**Comment by shuvashish76** [comment]
Seems the bug is still there.

```
FATAL EXCEPTION: Thread-2
Process: theredspy15.ltecleanerfoss, PID: 11644
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at f3.b.e(:5)
	at theredspy15.ltecleanerfoss.controllers.MainActivity.z(:14)
	at g3.b.run(:15)
	at java.lang.Thread.run(Thread.java:764)
```

- App Version : 4.9.7 (60) [F-Droid]

**Comment by shuvashish76** [comment]
@TheRedSpy15 reopen this issue please.
